service: nanyuan-web-app-services

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION}
  environment:
    EMAIL_FROM: ${env:EMAIL_FROM}
    EMAIL_TO: ${env:EMAIL_TO}
    SANITY_PROJECT_ID: ${env:SANITY_PROJECT_ID}
    SANITY_DATASET: ${env:SANITY_DATASET}
    SANITY_API_TOKEN: ${env:SANITY_API_TOKEN}
    ALLOW_ORIGIN: ${env:ALLOW_ORIGIN}

functions:
  sendEmail:
    handler: lambda/send-email.handler
    memorySize: 1024
    timeout: 15
    role: ServerlessNextjsLambdaRole 
    events:
      - http:
          path: api/send-email
          method: post
          cors: true
  createReservation:
    handler: lambda/create-reservation.handler
    memorySize: 1024
    timeout: 15
    role: ServerlessNextjsLambdaRole
    events:
      - http:
          path: api/create-reservation
          method: post
          cors:
            origins:
              - http://localhost:3000
              - ${env:CLIENT_BASE_URL}
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization

  createTakeawayOrder:
    handler: lambda/create-takeaway-order.handler
    memorySize: 1024
    timeout: 15
    role: ServerlessNextjsLambdaRole
    events:
      - http:
          path: api/create-takeaway-order
          method: post
          cors:
            origins:
              - http://localhost:3000
              - ${env:CLIENT_BASE_URL}
            methods:
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization

resources:
  Resources:
    ServerlessNextjsLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SendEmailPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                    - ses:SendRawEmail
                  Resource: "*"
