  update-comment:
    runs-on: ubuntu-latest
    name: Update PR Comment with Code Quality Badge
    needs: code-review
    steps:
      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          identifier: deepseek-review-comment
          body: |
            **AI Code Review Results:**
                        
            **Detailed Breakdown:**
            - **Code Readability:** _X/20 – [explanation]_
            - **Maintainability:** _Y/20 – [explanation]_
            - **Performance:** _Z/20 – [explanation]_
            - **Security:** _W/20 – [explanation]_
            - **Code Style:** _V/20 – [explanation]_
            
            **Overall Quality Score:** _Q/100_
            
            ${{ fromJson(needs.code-review.outputs.review_output || '{}').overall_comment }}
